name: 'Telegram Action Notifier'
description: 'Get a message when a build compile'
main: 'dist/index.js'
inputs:
  bot-token:
    description: 'The telegram bot token'
    required: true
  bot-chat-id:
    description: 'The telegram chat id where to send the message'
    required: true
  release-url:
    description: 'The telegram chat id where to send the message'
    required: true
  github-url:
    description: 'The telegram chat id where to send the message'
    required: true
  apple-url:
    description: 'The telegram chat id where to send the message'
    required: true
  app-name:
    description: 'The telegram chat id where to send the message'
    required: true
    default: 'App'
outputs:
  time:
    description: 'Time'
runs:
  using: 'node12'
  main: 'index.js'